---
driver:
  name: vagrant
  provider: libvirt
  vagrantfiles:
   - test/integration/Vagrantfile.rb

provisioner:
  name: chef_zero

# Uncomment the following verifier to leverage Inspec instead of Busser (the
# default verifier)
# verifier:
#   name: inspec

platforms:
  - name: centos-7.2

suites:
  - name: default
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[dmlb2000_docker::default]
    attributes:
  - name: server
    data_bags_path: "test/integration/data_bags"
    run_list:
      - recipe[dmlb2000_docker::server]
    attributes:
