name 'dmlb2000_docker'
maintainer 'David Brown'
maintainer_email 'dmlb2000@gmail.com'
license 'all_rights'
description 'Installs/Configures dmlb2000_docker'
long_description 'Installs/Configures dmlb2000_docker'
version '0.2.1'

depends 'lvm'
depends 'x509'
depends 'docker'
