default['x509']['country'] = 'US'
default['x509']['state'] = 'WA'
default['x509']['city'] = 'Richland'
default['x509']['organization'] = 'dmlb2000'
default['x509']['department'] = 'dmlb2000'
default['x509']['email'] = 'dmlb2000@gmail.com'

default['dmlb2000_docker']['certs']['ca']['pem'] = '/etc/pki/docker/docker-ca.pem'
default['dmlb2000_docker']['certs']['ca']['key'] = '/etc/pki/docker/docker-ca.key'
default['dmlb2000_docker']['certs']['ca']['cert'] = '/etc/pki/docker/docker-ca.cert'
default['dmlb2000_docker']['certs']['client']['key'] = '/etc/pki/docker/docker-client.key'
default['dmlb2000_docker']['certs']['client']['cert'] = '/etc/pki/docker/docker-client.cert'
default['dmlb2000_docker']['certs']['server']['key'] = '/etc/pki/docker/docker-server.key'
default['dmlb2000_docker']['certs']['server']['cert'] = '/etc/pki/docker/docker-server.cert'
